# Use root/example as user/password credentials
version: '3.1'

services:
  php-env:
    build: ./web
    volumes: 
      - ./web:/var/www/html
    ports:
      - 9000:80

  Mysql_db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes: 
        - ./init:/docker-entrypoint-initdb.d
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
  